insert into public.questions (id, topic, question_text, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3)
values  (1, 'Science', 'Quelle est la formule chimique de l''eau ?', 'H2O', 'CO2', 'O2', 'N2'),
        (2, 'Science', 'Combien de planètes y a-t-il dans le système solaire ?', '8', '9', '7', '10'),
        (3, 'Science', 'Quel est l''organe responsable de la production d''insuline ?', 'Le pancréas', 'Le foie', 'Le cerveau', 'Le rein'),
        (4, 'Science', 'Quelle est la vitesse de la lumière ?', '300000 km/s', '150000 km/s', '500000 km/s', '100000 km/s'),
        (5, 'Science', 'Quel est l''élément chimique symbole Fe ?', 'Le fer', 'Le fluor', 'Le cuivre', 'Le phosphore'),
        (6, 'Science', 'Qui a découvert la pénicilline ?', 'Alexander Fleming', 'Marie Curie', 'Louis Pasteur', 'Isaac Newton'),
        (7, 'Science', 'Combien de paires de chromosomes possèdent les humains ?', '23', '46', '22', '24'),
        (8, 'Science', 'Quel est le plus grand organe du corps humain ?', 'La peau', 'Le foie', 'Les poumons', 'Le cerveau'),
        (9, 'Science', 'Quelle est l''unité de mesure de la force ?', 'Newton', 'Joule', 'Watt', 'Pascal'),
        (10, 'Science', 'Combien de côtés possède un hexagone ?', '6', '5', '7', '8'),
        (11, 'Science', 'Quel gaz est essentiel à la respiration humaine ?', 'Oxygène', 'Hydrogène', 'Azote', 'Carbone'),
        (12, 'Science', 'Quelle est la planète la plus chaude du système solaire ?', 'Vénus', 'Mercure', 'Mars', 'Jupiter'),
        (13, 'Science', 'Quel est le symbole chimique de l''or ?', 'Au', 'Ag', 'O', 'Pt'),
        (14, 'Science', 'Quelle est l''unité de base de la matière ?', 'L''atome', 'La molécule', 'La cellule', 'Le neutron'),
        (15, 'Science', 'Quelle particule a une charge négative ?', 'Électron', 'Proton', 'Neutron', 'Photon'),
        (16, 'Science', 'Quelle force maintient les objets au sol ?', 'Gravité', 'Magnétisme', 'Force centrifuge', 'Inertie'),
        (17, 'Science', 'Quel est l''élément chimique symbole Na ?', 'Sodium', 'Nitrogène', 'Nickel', 'Neon'),
        (18, 'Science', 'Quelle étoile est la plus proche de la Terre ?', 'Le Soleil', 'Alpha Centauri', 'Sirius', 'Proxima Centauri'),
        (19, 'Science', 'Combien de couleurs contient un arc-en-ciel ?', '7', '6', '8', '5'),
        (20, 'Science', 'Quelle est la formule chimique du dioxyde de carbone ?', 'CO2', 'CO', 'C2O', 'O2'),
        (21, 'Histoire', 'En quelle année a eu lieu la Révolution française ?', '1789', '1776', '1804', '1914'),
        (22, 'Histoire', 'Qui a été le premier président des États-Unis ?', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 'Benjamin Franklin'),
        (23, 'Histoire', 'Quelle guerre est souvent considérée comme la première guerre mondiale ?', 'La Guerre de Sept Ans', 'La Guerre de Cent Ans', 'La Guerre de Trente Ans', 'La Guerre des Deux Roses'),
        (24, 'Histoire', 'Quel empereur a été couronné en 800 après JC ?', 'Charlemagne', 'Napoléon', 'Jules César', 'Alexandre le Grand'),
        (25, 'Histoire', 'Qui a mené la conquête normande de l''Angleterre en 1066 ?', 'Guillaume le Conquérant', 'Richard Cœur de Lion', 'Henri VIII', 'Édouard le Confesseur'),
        (26, 'Histoire', 'Quel traité a mis fin à la Première Guerre mondiale ?', 'Le traité de Versailles', 'Le traité de Paris', 'Le traité de Londres', 'Le traité de Genève'),
        (27, 'Histoire', 'Qui était le premier roi de France ?', 'Clovis', 'Charlemagne', 'Louis XIV', 'Charles Martel'),
        (28, 'Histoire', 'Quelle reine d''Angleterre a gouverné pendant l''époque élisabéthaine ?', 'Élisabeth I', 'Marie Stuart', 'Victoria', 'Anne'),
        (29, 'Histoire', 'En quelle année a eu lieu la chute de l''Empire romain ?', '476', '1492', '1066', '1000'),
        (30, 'Histoire', 'Qui a été le dernier tsar de Russie ?', 'Nicolas II', 'Pierre le Grand', 'Alexandre III', 'Ivan le Terrible'),
        (31, 'Histoire', 'Quelle révolution a eu lieu en 1917 ?', 'La révolution russe', 'La révolution américaine', 'La révolution française', 'La révolution chinoise'),
        (32, 'Histoire', 'Qui a été le principal architecte de la guerre froide ?', 'Winston Churchill', 'Joseph Staline', 'Franklin D. Roosevelt', 'Adolf Hitler'),
        (33, 'Histoire', 'Quel empire a été dirigé par Gengis Khan ?', 'L''empire mongol', 'L''empire ottoman', 'L''empire romain', 'L''empire perse'),
        (34, 'Histoire', 'Qui a mené l''expédition qui a découvert l''Amérique ?', 'Christophe Colomb', 'Vasco de Gama', 'Ferdinand Magellan', 'Amerigo Vespucci'),
        (35, 'Histoire', 'Quel roi de France a été exécuté pendant la Révolution française ?', 'Louis XVI', 'Louis XIV', 'Louis XVIII', 'Charles X'),
        (36, 'Histoire', 'Quel événement a déclenché la Première Guerre mondiale ?', 'L''assassinat de l''archiduc François-Ferdinand', 'La prise de la Bastille', 'L''attaque de Pearl Harbor', 'L''invasion de la Pologne'),
        (37, 'Histoire', 'Quel pays a été divisé par le mur de Berlin ?', 'L''Allemagne', 'La Russie', 'La France', 'La Pologne'),
        (38, 'Histoire', 'Qui a été le premier empereur de Chine ?', 'Qin Shi Huang', 'Mao Zedong', 'Sun Yat-sen', 'Confucius'),
        (39, 'Histoire', 'Quelle dynastie a régné en France pendant la Renaissance ?', 'Les Valois', 'Les Bourbon', 'Les Plantagenêt', 'Les Capétiens'),
        (40, 'Histoire', 'Quel est le nom du traité signé entre l''Angleterre et la France en 1420 ?', 'Le traité de Troyes', 'Le traité de Verdun', 'Le traité de Westphalie', 'Le traité de Picquigny'),
        (41, 'Géographie', 'Quelle est la capitale de la France ?', 'Paris', 'Londres', 'Berlin', 'Rome'),
        (42, 'Géographie', 'Quel est le plus grand continent du monde ?', 'Asie', 'Europe', 'Afrique', 'Amérique'),
        (43, 'Géographie', 'Quelle mer se trouve entre l''Europe et l''Afrique ?', 'La mer Méditerranée', 'La mer Rouge', 'L''Océan Atlantique', 'La mer Noire'),
        (44, 'Géographie', 'Quel est le plus grand océan du monde ?', 'Pacifique', 'Atlantique', 'Indien', 'Arctique'),
        (45, 'Géographie', 'Quelle est la plus haute montagne du monde ?', 'L''Everest', 'Le Kilimandjaro', 'Le Mont Blanc', 'Le Mont Fuji'),
        (46, 'Géographie', 'Quel pays a le plus grand nombre d''îles au monde ?', 'Suède', 'Indonésie', 'Philippines', 'Canada'),
        (47, 'Géographie', 'Quel désert est le plus vaste sur Terre ?', 'Le Sahara', 'Le désert de Gobi', 'Le Kalahari', 'Le désert d''Arabie'),
        (48, 'Géographie', 'Quelle chaîne de montagnes se trouve en Amérique du Sud ?', 'Les Andes', 'Les Rocheuses', 'Les Alpes', 'L''Himalaya'),
        (49, 'Géographie', 'Quelle est la capitale de l''Australie ?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane'),
        (50, 'Géographie', 'Quel fleuve traverse le plus de pays ?', 'Le Danube', 'Le Nil', 'Le Mississippi', 'Le Gange'),
        (51, 'Géographie', 'Quel est le pays le plus peuplé du continent africain ?', 'Nigeria', 'Égypte', 'Afrique du Sud', 'Éthiopie'),
        (52, 'Géographie', 'Quelle ville est située à la plus haute altitude ?', 'La Paz', 'Katmandou', 'Quito', 'Cusco'),
        (53, 'Géographie', 'Quel pays d''Asie a la plus longue frontière terrestre ?', 'Chine', 'Russie', 'Inde', 'Kazakhstan'),
        (54, 'Géographie', 'Quelle est la longueur approximative de la côte norvégienne, incluant les fjords ?', '100 915 km', '40 000 km', '15 000 km', '70 000 km'),
        (55, 'Géographie', 'Dans quelle région du globe trouve-t-on le désert le plus froid ?', 'L''Antarctique', 'Le Sahara', 'Le désert de Gobi', 'Le désert de Taklamakan'),
        (56, 'Géographie', 'Quelle est la capitale de la France ?', 'Paris', 'Londres', 'Berlin', 'Rome'),
        (57, 'Géographie', 'Quel est le plus grand continent du monde ?', 'Asie', 'Europe', 'Afrique', 'Amérique'),
        (323, 'Musique', 'Quel groupe a chanté "Bohemian Rhapsody" ?', 'Queen', 'The Beatles', 'Led Zeppelin', 'The Who'),
        (58, 'Géographie', 'Quelle mer se trouve entre l''Europe et l''Afrique ?', 'La mer Méditerranée', 'La mer Rouge', 'L''Océan Atlantique', 'La mer Noire'),
        (59, 'Géographie', 'Quel est le plus grand océan du monde ?', 'Pacifique', 'Atlantique', 'Indien', 'Arctique'),
        (60, 'Géographie', 'Quelle est la plus haute montagne du monde ?', 'L''Everest', 'Le Kilimandjaro', 'Le Mont Blanc', 'Le Mont Fuji'),
        (61, 'Géographie', 'Quel pays a le plus grand nombre d''îles au monde ?', 'Suède', 'Indonésie', 'Philippines', 'Canada'),
        (62, 'Géographie', 'Quel désert est le plus vaste sur Terre ?', 'Le Sahara', 'Le désert de Gobi', 'Le Kalahari', 'Le désert d''Arabie'),
        (63, 'Géographie', 'Quelle chaîne de montagnes se trouve en Amérique du Sud ?', 'Les Andes', 'Les Rocheuses', 'Les Alpes', 'L''Himalaya'),
        (64, 'Géographie', 'Quelle est la capitale de l''Australie ?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane'),
        (65, 'Géographie', 'Quel fleuve traverse le plus de pays ?', 'Le Danube', 'Le Nil', 'Le Mississippi', 'Le Gange'),
        (66, 'Géographie', 'Quelle est la capitale de la France ?', 'Paris', 'Londres', 'Berlin', 'Rome'),
        (67, 'Géographie', 'Quel est le plus grand continent du monde ?', 'Asie', 'Europe', 'Afrique', 'Amérique'),
        (68, 'Géographie', 'Quelle mer se trouve entre l''Europe et l''Afrique ?', 'La mer Méditerranée', 'La mer Rouge', 'L''Océan Atlantique', 'La mer Noire'),
        (69, 'Géographie', 'Quel est le plus grand océan du monde ?', 'Pacifique', 'Atlantique', 'Indien', 'Arctique'),
        (70, 'Géographie', 'Quelle est la plus haute montagne du monde ?', 'L''Everest', 'Le Kilimandjaro', 'Le Mont Blanc', 'Le Mont Fuji'),
        (71, 'Sport', 'Quel sport se joue avec une balle orange et deux paniers ?', 'Basketball', 'Football', 'Tennis', 'Volleyball'),
        (72, 'Sport', 'Combien de joueurs composent une équipe de football sur le terrain ?', '11', '10', '9', '12'),
        (73, 'Sport', 'Quel pays a remporté la Coupe du Monde de football en 2018 ?', 'France', 'Brésil', 'Argentine', 'Allemagne'),
        (74, 'Sport', 'Dans quel sport utilise-t-on un filet et une raquette ?', 'Tennis', 'Football', 'Golf', 'Rugby'),
        (75, 'Sport', 'Quel sport est pratiqué à Wimbledon ?', 'Tennis', 'Basketball', 'Cricket', 'Rugby'),
        (76, 'Sport', 'Quel coureur cycliste a remporté le Tour de France à 5 reprises ?', 'Miguel Indurain', 'Lance Armstrong', 'Eddy Merckx', 'Chris Froome'),
        (77, 'Sport', 'Quel sport est surnommé "le noble art" ?', 'La boxe', 'Le judo', 'Le karaté', 'L''escrime'),
        (78, 'Sport', 'Combien de grands chelems Roger Federer a-t-il remportés ?', '20', '18', '22', '24'),
        (79, 'Sport', 'Quel pays a remporté la première Coupe du Monde de football en 1930 ?', 'Uruguay', 'Brésil', 'Argentine', 'Allemagne'),
        (80, 'Sport', 'Dans quel sport utilise-t-on un "putter" ?', 'Golf', 'Tennis', 'Hockey sur glace', 'Basketball'),
        (81, 'Sport', 'Qui a été le premier champion du monde de Formule 1 ?', 'Giuseppe Farina', 'Ayrton Senna', 'Michael Schumacher', 'Juan Manuel Fangio'),
        (82, 'Sport', 'Quel est le plus long tournoi de tennis du Grand Chelem ?', 'Wimbledon', 'Roland Garros', 'US Open', 'Open d''Australie'),
        (83, 'Sport', 'Combien de médailles d''or Usain Bolt a-t-il remportées aux Jeux Olympiques ?', '8', '6', '10', '9'),
        (84, 'Sport', 'Quel joueur de basket est surnommé "His Airness" ?', 'Michael Jordan', 'LeBron James', 'Kobe Bryant', 'Shaquille O''Neal'),
        (85, 'Sport', 'Combien de tours le marathon olympique comporte-t-il ?', '42,195 km', '40 km', '45 km', '50 km'),
        (86, 'Musique', 'Quel groupe a écrit la chanson "Bohemian Rhapsody" ?', 'Queen', 'The Beatles', 'Pink Floyd', 'The Rolling Stones'),
        (87, 'Musique', 'Qui est le chanteur principal du groupe U2 ?', 'Bono', 'Freddie Mercury', 'Mick Jagger', 'Bruce Springsteen'),
        (88, 'Musique', 'Quel instrument a 88 touches ?', 'Le piano', 'La guitare', 'Le violon', 'La batterie'),
        (89, 'Musique', 'Quel genre musical est souvent associé à Bob Marley ?', 'Reggae', 'Jazz', 'Blues', 'Rock'),
        (90, 'Musique', 'Qui a chanté "Thriller" ?', 'Michael Jackson', 'Prince', 'Elton John', 'David Bowie'),
        (91, 'Musique', 'Quel compositeur est surnommé "Le roi de la valse" ?', 'Johann Strauss II', 'Frédéric Chopin', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart'),
        (92, 'Musique', 'Quel groupe de rock a pour membres Mick Jagger et Keith Richards ?', 'The Rolling Stones', 'The Beatles', 'Led Zeppelin', 'The Who'),
        (93, 'Musique', 'Quelle chanteuse a popularisé la chanson "Like a Virgin" ?', 'Madonna', 'Whitney Houston', 'Mariah Carey', 'Celine Dion'),
        (94, 'Musique', 'Quel instrument est principalement utilisé dans le jazz ?', 'Le saxophone', 'La guitare', 'Le violon', 'Le violoncelle'),
        (95, 'Musique', 'Quel compositeur a écrit la "Symphonie n°9 en ré mineur" ?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Antonio Vivaldi'),
        (96, 'Musique', 'Quel compositeur russe est l''auteur du ballet "Le Lac des cygnes" ?', 'Piotr Ilitch Tchaïkovski', 'Igor Stravinsky', 'Dmitri Chostakovitch', 'Sergueï Prokofiev'),
        (97, 'Musique', 'Quel artiste a vendu le plus d''albums dans le monde ?', 'The Beatles', 'Elvis Presley', 'Michael Jackson', 'Madonna'),
        (98, 'Musique', 'Quelle chanson des Beatles commence par "Yesterday, all my troubles seemed so far away..." ?', 'Yesterday', 'Hey Jude', 'Let It Be', 'Come Together'),
        (99, 'Musique', 'Dans quel pays est né Wolfgang Amadeus Mozart ?', 'Autriche', 'Allemagne', 'Italie', 'France'),
        (100, 'Musique', 'Quel musicien est surnommé "The King of Rock and Roll" ?', 'Elvis Presley', 'Chuck Berry', 'Little Richard', 'Jerry Lee Lewis'),
        (101, 'Technologie', 'Quelle entreprise a créé le système d''exploitation Windows ?', 'Microsoft', 'Apple', 'Google', 'IBM'),
        (102, 'Technologie', 'Quel réseau social a été fondé par Mark Zuckerberg ?', 'Facebook', 'Twitter', 'Instagram', 'LinkedIn'),
        (103, 'Technologie', 'Quel est le langage de programmation principalement utilisé pour le développement web côté client ?', 'JavaScript', 'Python', 'Java', 'C++'),
        (104, 'Technologie', 'Que signifie l''acronyme "CPU" ?', 'Central Processing Unit', 'Computer Power Unit', 'Central Power Unit', 'Computer Processing Unit'),
        (105, 'Technologie', 'Quelle entreprise fabrique les iPhones ?', 'Apple', 'Samsung', 'Huawei', 'Google'),
        (106, 'Technologie', 'Quel est le système d''exploitation le plus utilisé au monde ?', 'Windows', 'macOS', 'Linux', 'Android'),
        (107, 'Technologie', 'Quelle est la résolution standard d''un écran Full HD ?', '1920x1080', '1280x720', '2560x1440', '3840x2160'),
        (108, 'Technologie', 'Quel langage de programmation est principalement utilisé pour développer des applications Android ?', 'Java', 'Kotlin', 'Swift', 'C#'),
        (109, 'Technologie', 'Quel protocole est utilisé pour transférer des pages web ?', 'HTTP', 'FTP', 'SMTP', 'IMAP'),
        (110, 'Technologie', 'Quelle entreprise possède YouTube ?', 'Google', 'Facebook', 'Microsoft', 'Amazon'),
        (111, 'Technologie', 'En quelle année le premier iPhone a-t-il été lancé ?', '2007', '2005', '2010', '2003'),
        (112, 'Technologie', 'Qui est considéré comme le créateur du World Wide Web ?', 'Tim Berners-Lee', 'Bill Gates', 'Steve Jobs', 'Larry Page'),
        (113, 'Technologie', 'Quel est le nom du premier superordinateur à avoir dépassé la vitesse d’un petaflop ?', 'Roadrunner', 'Summit', 'Fugaku', 'Titan'),
        (114, 'Technologie', 'Quelle est la fréquence de rafraîchissement standard d’un écran de gaming ?', '144 Hz', '60 Hz', '120 Hz', '240 Hz'),
        (115, 'Technologie', 'Quel fut le premier langage de programmation moderne développé en 1957 ?', 'Fortran', 'COBOL', 'C', 'BASIC'),
        (116, 'Histoire', 'Quel événement marqua le début de la Première Guerre mondiale ?', 'L''assassinat de l''archiduc François-Ferdinand', 'Le bombardement de Pearl Harbor', 'La Révolution russe', 'Le traité de Versailles'),
        (117, 'Histoire', 'En quelle année la Révolution française a-t-elle commencé ?', '1789', '1776', '1799', '1815'),
        (118, 'Histoire', 'Qui était le président des États-Unis pendant la guerre civile américaine ?', 'Abraham Lincoln', 'George Washington', 'Franklin D. Roosevelt', 'John F. Kennedy'),
        (119, 'Histoire', 'Quel empire a été dirigé par Gengis Khan ?', 'L''Empire mongol', 'L''Empire romain', 'L''Empire perse', 'L''Empire ottoman'),
        (120, 'Histoire', 'Quelle bataille décisive a marqué la fin de Napoléon Bonaparte ?', 'La bataille de Waterloo', 'La bataille de Trafalgar', 'La bataille de Verdun', 'La bataille de Hastings'),
        (121, 'Histoire', 'Quel pays a été envahi par l''Allemagne en 1939, déclenchant la Seconde Guerre mondiale ?', 'La Pologne', 'La France', 'Le Royaume-Uni', 'La Russie'),
        (122, 'Histoire', 'Qui était le premier empereur de la Chine unifiée ?', 'Qin Shi Huang', 'Sun Yat-sen', 'Liu Bang', 'Mao Zedong'),
        (123, 'Histoire', 'Quel traité a officiellement mis fin à la Première Guerre mondiale ?', 'Le traité de Versailles', 'Le traité de Tordesillas', 'Le traité de Yalta', 'Le pacte de Varsovie'),
        (124, 'Histoire', 'Qui a découvert l''Amérique en 1492 ?', 'Christophe Colomb', 'Leif Erikson', 'Marco Polo', 'Vasco de Gama'),
        (125, 'Histoire', 'Quelle dynastie a régné sur la France pendant plus de 300 ans ?', 'Les Capétiens', 'Les Plantagenêts', 'Les Habsbourg', 'Les Tudors'),
        (126, 'Histoire', 'Quel mur célèbre séparait Berlin pendant la Guerre froide ?', 'Le mur de Berlin', 'Le rideau de fer', 'Le mur de l''Atlantique', 'Le mur de Staline'),
        (127, 'Histoire', 'En quelle année la chute du mur de Berlin a-t-elle eu lieu ?', '1989', '1991', '1979', '1969'),
        (128, 'Histoire', 'Qui était le premier président de la République française ?', 'Louis-Napoléon Bonaparte', 'Charles de Gaulle', 'Jules Ferry', 'François Mitterrand'),
        (129, 'Histoire', 'Quel pharaon est célèbre pour sa tombe intacte découverte en 1922 ?', 'Toutânkhamon', 'Ramsès II', 'Cléopâtre', 'Akhenaton'),
        (130, 'Histoire', 'Quel conflit a opposé l''Union et la Confédération ?', 'La guerre de Sécession', 'La guerre d''indépendance américaine', 'La guerre de Crimée', 'La guerre de Cent Ans'),
        (131, 'Histoire', 'Qui était le dictateur de l''Allemagne nazie ?', 'Adolf Hitler', 'Benito Mussolini', 'Joseph Staline', 'Winston Churchill'),
        (132, 'Histoire', 'Quel pays a été dirigé par le tsar Nicolas II avant la Révolution russe ?', 'La Russie', 'La France', 'L''Allemagne', 'L''Autriche-Hongrie'),
        (133, 'Histoire', 'Quelle célèbre bataille a eu lieu en 1066 ?', 'La bataille de Hastings', 'La bataille de Verdun', 'La bataille de Stalingrad', 'La bataille de la Somme'),
        (134, 'Histoire', 'Qui était le premier Premier ministre de l''Inde après l''indépendance ?', 'Jawaharlal Nehru', 'Mahatma Gandhi', 'Indira Gandhi', 'Subhas Chandra Bose'),
        (135, 'Histoire', 'En quelle année l''Empire romain d''Occident s''est-il effondré ?', '476', '395', '1492', '800'),
        (136, 'Histoire', 'Qui fut le premier président des États-Unis ?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'),
        (137, 'Histoire', 'Quel événement historique a eu lieu le 14 juillet 1789 en France ?', 'La prise de la Bastille', 'La proclamation de la République', 'La chute de Napoléon', 'Le couronnement de Louis XVI'),
        (138, 'Histoire', 'Quel explorateur portugais fut le premier à atteindre les Indes par la mer ?', 'Vasco de Gama', 'Christophe Colomb', 'Ferdinand Magellan', 'Bartolomeu Dias'),
        (139, 'Histoire', 'Quelle révolution a commencé en Russie en 1917 ?', 'La Révolution russe', 'La Révolution industrielle', 'La Révolution française', 'La Révolution américaine'),
        (140, 'Histoire', 'Qui a été couronné empereur d''Occident en 800 ?', 'Charlemagne', 'Jules César', 'Auguste', 'Frédéric Barberousse'),
        (141, 'Histoire', 'Quel pays a été dirigé par la dynastie des Tudor ?', 'L''Angleterre', 'La France', 'L''Espagne', 'Le Portugal'),
        (142, 'Histoire', 'En quelle année a eu lieu la bataille de Normandie ?', '1944', '1945', '1940', '1939'),
        (143, 'Histoire', 'Quel est le nom du célèbre discours prononcé par Martin Luther King en 1963 ?', 'I have a dream', 'Yes we can', 'Liberté, Égalité, Fraternité', 'We shall overcome'),
        (144, 'Histoire', 'Quel mouvement politique a été dirigé par Adolf Hitler ?', 'Le nazisme', 'Le fascisme', 'Le communisme', 'Le socialisme'),
        (145, 'Histoire', 'En quelle année la guerre d''indépendance des États-Unis s''est-elle terminée ?', '1783', '1776', '1791', '1801'),
        (146, 'Histoire', 'Quel événement a marqué la fin de la guerre froide ?', 'La chute du mur de Berlin', 'L''attaque de Pearl Harbor', 'Le traité de Versailles', 'La crise des missiles de Cuba'),
        (147, 'Histoire', 'Quel dirigeant égyptien a construit les grandes pyramides de Gizeh ?', 'Khéops', 'Toutânkhamon', 'Ramsès II', 'Akhenaton'),
        (148, 'Histoire', 'Qui a été le premier homme à marcher sur la Lune ?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'),
        (149, 'Histoire', 'Quel empire a construit le Colisée à Rome ?', 'L''Empire romain', 'L''Empire grec', 'L''Empire byzantin', 'L''Empire ottoman'),
        (150, 'Histoire', 'Quelle guerre a eu lieu entre 1950 et 1953 ?', 'La guerre de Corée', 'La guerre du Vietnam', 'La guerre de Crimée', 'La guerre d''Afghanistan'),
        (151, 'Histoire', 'Quel traité a mis fin à la Première Guerre mondiale ?', 'Le traité de Versailles', 'Le traité de Trianon', 'Le traité de Paris', 'Le traité de Vienne'),
        (152, 'Histoire', 'Quel pays a été fondé par Simon Bolivar ?', 'La Grande Colombie', 'Le Pérou', 'Le Chili', 'Le Brésil'),
        (153, 'Histoire', 'Quel royaume africain est devenu célèbre grâce à sa richesse en or et en sel ?', 'L''Empire du Mali', 'L''Empire du Ghana', 'L''Empire songhaï', 'L''Empire zoulou'),
        (154, 'Histoire', 'En quelle année a eu lieu la bataille de Verdun ?', '1916', '1914', '1918', '1940'),
        (155, 'Histoire', 'Quel empire a été dirigé par Alexandre le Grand ?', 'L''Empire macédonien', 'L''Empire romain', 'L''Empire byzantin', 'L''Empire perse'),
        (156, 'Histoire', 'Qui était le premier homme à marcher sur la Lune ?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins'),
        (157, 'Histoire', 'En quelle année l''Union européenne a-t-elle été créée officiellement ?', '1993', '1957', '2000', '1999'),
        (158, 'Histoire', 'Quel était le nom de code du débarquement de Normandie en 1944 ?', 'Opération Overlord', 'Opération Barbarossa', 'Opération Market Garden', 'Opération Dynamo'),
        (159, 'Histoire', 'Qui fut le premier roi de France sacré à Reims ?', 'Clovis I', 'Charlemagne', 'Louis XIV', 'Philippe II'),
        (160, 'Histoire', 'Quel événement a conduit à l''entrée en guerre des États-Unis pendant la Seconde Guerre mondiale ?', 'L''attaque de Pearl Harbor', 'L''invasion de la Pologne', 'La bataille de Midway', 'Le traité de Versailles'),
        (161, 'Histoire', 'Quel traité a marqué la fin de la guerre franco-prussienne ?', 'Le traité de Francfort', 'Le traité de Vienne', 'Le traité de Paris', 'Le traité de Versailles'),
        (162, 'Histoire', 'Quelle civilisation a construit Machu Picchu ?', 'Les Incas', 'Les Aztèques', 'Les Mayas', 'Les Olmèques'),
        (163, 'Histoire', 'Qui fut le dernier empereur de Russie avant la Révolution de 1917 ?', 'Nicolas II', 'Pierre le Grand', 'Alexandre III', 'Ivan le Terrible'),
        (164, 'Histoire', 'Quelle reine égyptienne est connue pour sa liaison avec Jules César et Marc Antoine ?', 'Cléopâtre', 'Néfertiti', 'Hatshepsout', 'Cléopâtre II'),
        (165, 'Histoire', 'Quelle guerre a eu lieu entre 1950 et 1953 ?', 'La guerre de Corée', 'La guerre du Vietnam', 'La guerre froide', 'La guerre des Malouines'),
        (166, 'Histoire', 'Qui a dirigé l''Afrique du Sud pendant l''apartheid ?', 'Nelson Mandela', 'F.W. de Klerk', 'Desmond Tutu', 'P.W. Botha'),
        (167, 'Histoire', 'Quelle est la plus longue dynastie de l''histoire de la Chine ?', 'Les Zhou', 'Les Qing', 'Les Ming', 'Les Tang'),
        (168, 'Histoire', 'En quelle année a eu lieu la crise des missiles de Cuba ?', '1962', '1959', '1975', '1967'),
        (169, 'Histoire', 'Quel dirigeant romain a été assassiné en 44 avant J.-C. ?', 'Jules César', 'Auguste', 'Pompée', 'Marc Antoine'),
        (170, 'Histoire', 'Quelle bataille a marqué la fin de l''Empire inca en 1532 ?', 'La bataille de Cajamarca', 'La bataille de Waterloo', 'La bataille d''Actium', 'La bataille de Hastings'),
        (171, 'Histoire', 'Quel pays a utilisé pour la première fois des chars lors de la Première Guerre mondiale ?', 'Le Royaume-Uni', 'La France', 'L''Allemagne', 'Les États-Unis'),
        (172, 'Histoire', 'Quel président américain a démissionné en 1974 à la suite du scandale du Watergate ?', 'Richard Nixon', 'Gerald Ford', 'John F. Kennedy', 'Lyndon B. Johnson'),
        (173, 'Histoire', 'Quelle grande route commerciale traversait l''Asie et reliait la Chine à l''Occident ?', 'La route de la soie', 'La voie romaine', 'Le passage du Nord-Ouest', 'La route de l''ambre'),
        (174, 'Histoire', 'Qui fut le premier empereur de l''Empire romain ?', 'Auguste', 'Néron', 'Caligula', 'Constantin'),
        (175, 'Histoire', 'Quel roi d''Angleterre fut décapité en 1649 à la suite de la guerre civile ?', 'Charles I', 'Henri VIII', 'Richard III', 'Édouard II'),
        (176, 'Science', 'Quel est l''élément chimique dont le symbole est O ?', 'L''oxygène', 'L''hydrogène', 'L''azote', 'Le carbone'),
        (177, 'Science', 'Quelle est la planète la plus proche du Soleil ?', 'Mercure', 'Vénus', 'Mars', 'Jupiter'),
        (178, 'Science', 'Qui a développé la théorie de la relativité ?', 'Albert Einstein', 'Isaac Newton', 'Galilée', 'Niels Bohr'),
        (179, 'Science', 'Quel est le plus gros organe du corps humain ?', 'La peau', 'Le foie', 'Le cerveau', 'Les poumons'),
        (180, 'Science', 'Quelle est la vitesse de la lumière dans le vide ?', '300 000 km/s', '150 000 km/s', '500 000 km/s', '1 000 000 km/s'),
        (181, 'Science', 'Quelle est la formule chimique de l''eau ?', 'H2O', 'CO2', 'O2', 'H2SO4'),
        (182, 'Science', 'Quelle planète est surnommée la planète rouge ?', 'Mars', 'Saturne', 'Jupiter', 'Mercure'),
        (183, 'Science', 'Quel est l''acide utilisé dans les batteries de voiture ?', 'Acide sulfurique', 'Acide acétique', 'Acide citrique', 'Acide chlorhydrique'),
        (184, 'Science', 'Quelle loi de Newton traite de l''action et de la réaction ?', 'La troisième loi de Newton', 'La première loi de Newton', 'La loi de la gravitation universelle', 'La deuxième loi de Newton'),
        (185, 'Science', 'Quel gaz est essentiel à la respiration humaine ?', 'L''oxygène', 'Le dioxyde de carbone', 'L''hydrogène', 'L''azote'),
        (186, 'Science', 'Quelle unité est utilisée pour mesurer la force d''un courant électrique ?', 'L''ampère', 'Le volt', 'Le watt', 'Le joule'),
        (187, 'Science', 'Quel scientifique a découvert la pénicilline ?', 'Alexander Fleming', 'Marie Curie', 'Louis Pasteur', 'Joseph Lister'),
        (188, 'Science', 'Quel est le plus petit os du corps humain ?', 'L''étrier', 'Le fémur', 'Le cubitus', 'Le métacarpe'),
        (189, 'Science', 'Quel est le gaz le plus abondant dans l''atmosphère terrestre ?', 'L''azote', 'L''oxygène', 'Le dioxyde de carbone', 'L''argon'),
        (190, 'Science', 'Quelle est l''énergie potentielle stockée dans un objet en mouvement ?', 'L''énergie cinétique', 'L''énergie potentielle', 'L''énergie thermique', 'L''énergie nucléaire'),
        (191, 'Science', 'Quel est l''organe responsable de la production de l''insuline dans le corps humain ?', 'Le pancréas', 'Le foie', 'Les reins', 'La rate'),
        (192, 'Science', 'Quel est le métal le plus léger ?', 'Le lithium', 'Le fer', 'Le cuivre', 'L''aluminium'),
        (193, 'Science', 'Qui a formulé les lois de la gravitation universelle ?', 'Isaac Newton', 'Galilée', 'Albert Einstein', 'Johannes Kepler'),
        (194, 'Science', 'Quel type d''animal est un ornithorynque ?', 'Un mammifère', 'Un reptile', 'Un oiseau', 'Un amphibien'),
        (195, 'Science', 'Quel est le point de congélation de l''eau en degrés Celsius ?', '0 °C', '32 °C', '-273 °C', '100 °C'),
        (196, 'Science', 'Quel est l''élément chimique dont le symbole est "O" ?', 'L''oxygène', 'L''or', 'L''osmium', 'L''oxalate'),
        (197, 'Science', 'Quelle planète est la plus proche du Soleil ?', 'Mercure', 'Vénus', 'Terre', 'Mars'),
        (198, 'Science', 'Qui a formulé la théorie de la relativité ?', 'Albert Einstein', 'Isaac Newton', 'Galilée', 'Niels Bohr'),
        (199, 'Science', 'Quel est le plus grand organe du corps humain ?', 'La peau', 'Le foie', 'Le cœur', 'Le cerveau'),
        (200, 'Science', 'Quel est le principal gaz qui compose l''atmosphère de la Terre ?', 'L''azote', 'L''oxygène', 'Le dioxyde de carbone', 'L''argon'),
        (201, 'Science', 'Quelle est la distance moyenne entre la Terre et le Soleil ?', '150 millions de kilomètres', '100 millions de kilomètres', '200 millions de kilomètres', '250 millions de kilomètres'),
        (202, 'Science', 'Quel est l''élément chimique le plus léger ?', 'L''hydrogène', 'L''hélium', 'L''oxygène', 'Le lithium'),
        (203, 'Science', 'Quelle est l''unité de mesure de la force ?', 'Le newton', 'Le joule', 'Le watt', 'Le hertz'),
        (204, 'Science', 'Quelle planète est surnommée la "Planète rouge" ?', 'Mars', 'Jupiter', 'Saturne', 'Vénus'),
        (205, 'Science', 'Quel scientifique a découvert la pénicilline ?', 'Alexander Fleming', 'Marie Curie', 'Louis Pasteur', 'Charles Darwin'),
        (206, 'Science', 'Quelle est la formule chimique de l''eau ?', 'H2O', 'CO2', 'O2', 'H2SO4'),
        (207, 'Science', 'Quelle est la vitesse de la lumière dans le vide ?', '300 000 km/s', '150 000 km/s', '1 million km/s', '450 000 km/s'),
        (208, 'Science', 'Quelle est l''unité de mesure de l''intensité électrique ?', 'L''ampère', 'Le volt', 'Le watt', 'Le joule'),
        (209, 'Science', 'Qui est considéré comme le père de la théorie de l''évolution ?', 'Charles Darwin', 'Gregor Mendel', 'Isaac Newton', 'Louis Pasteur'),
        (210, 'Science', 'Quelle est la planète la plus grande du système solaire ?', 'Jupiter', 'Saturne', 'Neptune', 'Uranus'),
        (211, 'Science', 'Quelle force maintient les planètes en orbite autour du Soleil ?', 'La gravité', 'Le magnétisme', 'La force centrifuge', 'La force nucléaire'),
        (212, 'Science', 'Quel est le point de congélation de l''eau à pression normale ?', '0°C', '100°C', '-273°C', '50°C'),
        (213, 'Science', 'Qui a inventé le télescope ?', 'Hans Lippershey', 'Galilée', 'Isaac Newton', 'Albert Einstein'),
        (214, 'Science', 'Quel est le plus petit os du corps humain ?', 'L''étrier', 'Le fémur', 'Le cubitus', 'La clavicule'),
        (215, 'Science', 'Quel gaz est essentiel pour la respiration humaine ?', 'L''oxygène', 'Le dioxyde de carbone', 'L''azote', 'L''hélium'),
        (216, 'Géographie', 'Quel est le plus long fleuve du monde ?', 'Le Nil', 'L''Amazone', 'Le Mississippi', 'Le Yangtsé'),
        (217, 'Géographie', 'Quel est le plus grand désert du monde ?', 'Le désert du Sahara', 'Le désert de Gobi', 'Le désert du Kalahari', 'Le désert de l''Atacama'),
        (218, 'Géographie', 'Dans quel pays se trouve la Tour Eiffel ?', 'France', 'Italie', 'Espagne', 'Belgique'),
        (219, 'Géographie', 'Quel est le pays le plus peuplé du monde ?', 'La Chine', 'L''Inde', 'Les États-Unis', 'Le Brésil'),
        (220, 'Géographie', 'Quel est le plus grand océan du monde ?', 'L''océan Pacifique', 'L''océan Atlantique', 'L''océan Indien', 'L''océan Arctique'),
        (221, 'Géographie', 'Quelle est la capitale du Canada ?', 'Ottawa', 'Toronto', 'Vancouver', 'Montréal'),
        (222, 'Géographie', 'Quel est le plus haut sommet du monde ?', 'L''Everest', 'Le K2', 'Le Kangchenjunga', 'Le Mont Blanc'),
        (223, 'Géographie', 'Dans quel pays se trouve la Grande Muraille ?', 'Chine', 'Japon', 'Corée du Sud', 'Inde'),
        (224, 'Géographie', 'Quel pays a la plus grande superficie du monde ?', 'La Russie', 'Le Canada', 'La Chine', 'Les États-Unis'),
        (225, 'Géographie', 'Quelle est la mer la plus salée du monde ?', 'La mer Morte', 'La mer Rouge', 'La mer Méditerranée', 'La mer Noire'),
        (226, 'Géographie', 'Quel est le plus grand continent en superficie ?', 'L''Asie', 'L''Afrique', 'L''Amérique du Nord', 'L''Europe'),
        (227, 'Géographie', 'Quelle ville est traversée par le fleuve Nil ?', 'Le Caire', 'Alexandrie', 'Khartoum', 'Nairobi'),
        (228, 'Géographie', 'Quelle est la capitale de l''Australie ?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane'),
        (229, 'Géographie', 'Quel est le plus petit pays du monde ?', 'Le Vatican', 'Monaco', 'Saint-Marin', 'Liechtenstein'),
        (230, 'Géographie', 'Quel est le plus grand lac d''eau douce du monde ?', 'Le lac Baïkal', 'Le lac Supérieur', 'Le lac Victoria', 'Le lac Tanganyika'),
        (231, 'Géographie', 'Dans quel océan se trouvent les Maldives ?', 'L''océan Indien', 'L''océan Atlantique', 'L''océan Pacifique', 'L''océan Arctique'),
        (232, 'Géographie', 'Quelle est la plus grande île du monde ?', 'Le Groenland', 'L''Australie', 'La Nouvelle-Guinée', 'Bornéo'),
        (233, 'Géographie', 'Quel est le pays d''Afrique avec la plus grande population ?', 'Le Nigeria', 'L''Égypte', 'L''Afrique du Sud', 'Le Kenya'),
        (234, 'Géographie', 'Quel est le fleuve qui traverse la ville de Londres ?', 'La Tamise', 'La Seine', 'Le Rhin', 'Le Rhône'),
        (235, 'Géographie', 'Dans quel pays se trouve le mont Kilimandjaro ?', 'La Tanzanie', 'Le Kenya', 'L''Éthiopie', 'L''Ouganda'),
        (236, 'Géographie', 'Quel est le plus grand pays du monde par superficie ?', 'La Russie', 'Le Canada', 'La Chine', 'Les États-Unis'),
        (237, 'Géographie', 'Quelle est la capitale de l''Australie ?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane'),
        (238, 'Géographie', 'Quel est le plus long fleuve du monde ?', 'Le Nil', 'L''Amazone', 'Le Mississippi', 'Le Yangzi Jiang'),
        (239, 'Géographie', 'Quel désert est le plus grand du monde ?', 'Le Sahara', 'Le désert de Gobi', 'Le désert de Kalahari', 'Le désert d''Atacama'),
        (240, 'Géographie', 'Quel est le plus haut sommet du monde ?', 'L''Everest', 'Le K2', 'Le Kangchenjunga', 'Le Mont Blanc'),
        (241, 'Géographie', 'Dans quel océan se trouve l''île de Madagascar ?', 'L''océan Indien', 'L''océan Atlantique', 'L''océan Pacifique', 'L''océan Arctique'),
        (242, 'Géographie', 'Quelle mer borde la côte est de l''Italie ?', 'La mer Adriatique', 'La mer Méditerranée', 'La mer Égée', 'La mer Noire'),
        (243, 'Géographie', 'Quel est le plus grand lac d''eau douce du monde par volume ?', 'Le lac Baïkal', 'Le lac Supérieur', 'Le lac Victoria', 'Le lac Tanganyika'),
        (244, 'Géographie', 'Quel pays a le plus grand nombre d''îles ?', 'La Suède', 'Les Philippines', 'Le Japon', 'La Grèce'),
        (245, 'Géographie', 'Quel pays est connu pour avoir le plus grand nombre de volcans actifs ?', 'L''Indonésie', 'L''Italie', 'Le Japon', 'L''Islande'),
        (246, 'Géographie', 'Quel fleuve traverse Paris ?', 'La Seine', 'La Loire', 'Le Rhône', 'Le Danube'),
        (247, 'Géographie', 'Quelle est la plus grande ville du Brésil ?', 'São Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador'),
        (248, 'Géographie', 'Quel est le plus petit pays du monde ?', 'Le Vatican', 'Monaco', 'Saint-Marin', 'Les Maldives'),
        (249, 'Géographie', 'Quel est le plus grand océan du monde ?', 'L''océan Pacifique', 'L''océan Atlantique', 'L''océan Indien', 'L''océan Arctique'),
        (250, 'Géographie', 'Dans quel pays se trouve le Kilimandjaro ?', 'La Tanzanie', 'Le Kenya', 'L''Afrique du Sud', 'Le Rwanda'),
        (251, 'Géographie', 'Quel continent compte le plus grand nombre de pays ?', 'L''Afrique', 'L''Asie', 'L''Europe', 'L''Amérique du Sud'),
        (252, 'Géographie', 'Quelle est la plus grande île du monde ?', 'Le Groenland', 'L''Australie', 'Bornéo', 'La Nouvelle-Guinée'),
        (253, 'Géographie', 'Quel est le pays le plus peuplé du monde ?', 'La Chine', 'L''Inde', 'Les États-Unis', 'L''Indonésie'),
        (254, 'Géographie', 'Quelle est la capitale du Canada ?', 'Ottawa', 'Toronto', 'Vancouver', 'Montréal'),
        (255, 'Géographie', 'Dans quel pays se trouve le désert de Gobi ?', 'La Mongolie', 'La Chine', 'Le Kazakhstan', 'L''Inde'),
        (256, 'Géographie', 'Quel est le plus grand désert du monde ?', 'Le désert du Sahara', 'Le désert de Gobi', 'Le désert d''Atacama', 'Le désert des Mojaves'),
        (257, 'Géographie', 'Quelle est la plus haute montagne du monde ?', 'L''Everest', 'Le K2', 'Le Kilimandjaro', 'Le Mont Blanc'),
        (258, 'Géographie', 'Quel est le plus long fleuve du monde ?', 'Le Nil', 'L''Amazone', 'Le Mississippi', 'Le Yangzi Jiang'),
        (259, 'Géographie', 'Quelle est la capitale de l''Australie ?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'),
        (260, 'Géographie', 'Quel est le plus grand pays du monde en superficie ?', 'La Russie', 'Le Canada', 'Les États-Unis', 'La Chine'),
        (261, 'Géographie', 'Quelle mer borde la ville de Venise ?', 'La mer Adriatique', 'La mer Méditerranée', 'La mer Noire', 'La mer Baltique'),
        (262, 'Géographie', 'Dans quel pays se trouve la Tour Eiffel ?', 'La France', 'L''Italie', 'L''Espagne', 'La Belgique'),
        (263, 'Géographie', 'Quel pays possède le plus grand nombre de lacs ?', 'Le Canada', 'La Finlande', 'La Suède', 'La Russie'),
        (264, 'Géographie', 'Quelle rivière traverse la ville de Londres ?', 'La Tamise', 'La Seine', 'Le Rhin', 'Le Danube'),
        (265, 'Géographie', 'Dans quel océan se trouve Madagascar ?', 'L''océan Indien', 'L''océan Atlantique', 'L''océan Pacifique', 'L''océan Arctique'),
        (266, 'Géographie', 'Quel est le pays le plus peuplé du monde ?', 'La Chine', 'L''Inde', 'Les États-Unis', 'Le Brésil'),
        (267, 'Géographie', 'Quel est le plus grand lac d''eau douce au monde ?', 'Le lac Baïkal', 'Le lac Victoria', 'Le lac Supérieur', 'Le lac Tanganyika'),
        (268, 'Géographie', 'Quel pays est connu pour ses pyramides anciennes ?', 'L''Égypte', 'Le Mexique', 'La Grèce', 'L''Inde'),
        (269, 'Géographie', 'Quel est le plus grand océan du monde ?', 'L''océan Pacifique', 'L''océan Atlantique', 'L''océan Indien', 'L''océan Arctique'),
        (270, 'Géographie', 'Quelle chaîne de montagnes sépare l''Europe de l''Asie ?', 'Les montagnes de l''Oural', 'Les Alpes', 'Les Pyrénées', 'Les Andes'),
        (271, 'Géographie', 'Quel pays a la plus grande population musulmane ?', 'L''Indonésie', 'L''Arabie saoudite', 'Le Pakistan', 'L''Iran'),
        (272, 'Géographie', 'Quelle ville est connue sous le nom de "la ville éternelle" ?', 'Rome', 'Athènes', 'Le Caire', 'Istanbul'),
        (273, 'Géographie', 'Quel pays est célèbre pour sa Grande Muraille ?', 'La Chine', 'Le Japon', 'La Corée du Sud', 'La Mongolie'),
        (274, 'Géographie', 'Quelle mer est la plus salée du monde ?', 'La mer Morte', 'La mer Rouge', 'La mer Noire', 'La mer Méditerranée'),
        (275, 'Géographie', 'Quelle est la capitale du Canada ?', 'Ottawa', 'Toronto', 'Vancouver', 'Montréal'),
        (276, 'Musique', 'Quel compositeur a écrit la Symphonie n° 9 en ré mineur, également connue sous le nom de "Symphonie de la joie" ?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Franz Schubert'),
        (277, 'Musique', 'Quel groupe britannique est connu pour des chansons comme "Hey Jude" et "Let It Be" ?', 'The Beatles', 'The Rolling Stones', 'Queen', 'Led Zeppelin'),
        (278, 'Musique', 'Quel chanteur est surnommé "Le Roi du Pop" ?', 'Michael Jackson', 'Elvis Presley', 'Prince', 'Stevie Wonder'),
        (279, 'Musique', 'Quel genre de musique est originaire de la Nouvelle-Orléans et est caractérisé par l’improvisation ?', 'Le jazz', 'Le blues', 'Le rock', 'Le reggae'),
        (280, 'Musique', 'Quel groupe a sorti l''album "Dark Side of the Moon" ?', 'Pink Floyd', 'The Who', 'Led Zeppelin', 'Genesis'),
        (281, 'Musique', 'Quel musicien est surnommé "Le Roi du Rock and Roll" ?', 'Elvis Presley', 'Chuck Berry', 'Buddy Holly', 'Little Richard'),
        (282, 'Musique', 'Quel instrument de musique a été inventé par Adolphe Sax ?', 'Le saxophone', 'La trompette', 'Le violoncelle', 'Le tuba'),
        (283, 'Musique', 'Qui est l''auteur de l''œuvre "La Flûte enchantée" ?', 'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Frédéric Chopin', 'Antonio Vivaldi'),
        (284, 'Musique', 'Quel genre de musique est associé à Bob Marley ?', 'Le reggae', 'Le blues', 'Le jazz', 'La soul'),
        (285, 'Musique', 'Quelle chanteuse est connue pour la chanson "Like a Virgin" ?', 'Madonna', 'Whitney Houston', 'Celine Dion', 'Mariah Carey'),
        (286, 'Musique', 'Quel groupe est à l''origine de la chanson "Bohemian Rhapsody" ?', 'Queen', 'The Beatles', 'The Rolling Stones', 'AC/DC'),
        (287, 'Musique', 'Quel compositeur est célèbre pour ses œuvres telles que "Les Quatre Saisons" ?', 'Antonio Vivaldi', 'Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Franz Schubert'),
        (288, 'Musique', 'Qui a interprété la chanson "Purple Rain" ?', 'Prince', 'Michael Jackson', 'Stevie Wonder', 'James Brown'),
        (289, 'Musique', 'Quel style de musique est caractérisé par des paroles parlées plutôt que chantées, souvent sur un beat rythmé ?', 'Le rap', 'Le jazz', 'La soul', 'Le rock'),
        (290, 'Musique', 'Quel groupe est connu pour l''album "Abbey Road" ?', 'The Beatles', 'The Rolling Stones', 'Led Zeppelin', 'Pink Floyd'),
        (291, 'Musique', 'Quel compositeur français est célèbre pour son "Boléro" ?', 'Maurice Ravel', 'Claude Debussy', 'Georges Bizet', 'Camille Saint-Saëns'),
        (292, 'Musique', 'Quel artiste est connu pour la chanson "Imagine" ?', 'John Lennon', 'Paul McCartney', 'George Harrison', 'Elton John'),
        (293, 'Musique', 'Quel chanteur a popularisé la chanson "What a Wonderful World" ?', 'Louis Armstrong', 'Ray Charles', 'Frank Sinatra', 'Nat King Cole'),
        (294, 'Musique', 'Quel genre musical est fortement associé à l''Espagne, avec des danseurs et des guitaristes ?', 'Le flamenco', 'Le tango', 'La samba', 'La bossa nova'),
        (295, 'Musique', 'Qui est le compositeur de l''opéra "Carmen" ?', 'Georges Bizet', 'Giuseppe Verdi', 'Richard Wagner', 'Wolfgang Amadeus Mozart'),
        (296, 'Musique', 'Quel compositeur est célèbre pour sa Symphonie n°9 ?', 'Ludwig van Beethoven', 'Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Franz Schubert'),
        (297, 'Musique', 'Quel groupe britannique est connu pour l''album "Abbey Road" ?', 'The Beatles', 'The Rolling Stones', 'Pink Floyd', 'Queen'),
        (298, 'Musique', 'Quel chanteur est surnommé "le roi du rock and roll" ?', 'Elvis Presley', 'Michael Jackson', 'Chuck Berry', 'Little Richard'),
        (299, 'Musique', 'Quel instrument a quatre cordes et est plus petit qu''une guitare ?', 'Le ukulélé', 'Le violon', 'La mandoline', 'La basse'),
        (300, 'Musique', 'Quelle chanteuse est connue pour la chanson "Like a Virgin" ?', 'Madonna', 'Whitney Houston', 'Celine Dion', 'Mariah Carey'),
        (301, 'Musique', 'Quel compositeur est célèbre pour son opéra "La Flûte enchantée" ?', 'Wolfgang Amadeus Mozart', 'Richard Wagner', 'Giuseppe Verdi', 'Johann Strauss II'),
        (302, 'Musique', 'Quel est l''instrument principal de Miles Davis ?', 'La trompette', 'Le saxophone', 'Le piano', 'La guitare'),
        (303, 'Musique', 'Qui a interprété la chanson "Thriller" ?', 'Michael Jackson', 'Prince', 'Stevie Wonder', 'Lionel Richie'),
        (304, 'Musique', 'Quel groupe est connu pour la chanson "Bohemian Rhapsody" ?', 'Queen', 'The Beatles', 'Led Zeppelin', 'Pink Floyd'),
        (305, 'Musique', 'Quel musicien classique a perdu l''usage de son audition ?', 'Ludwig van Beethoven', 'Frédéric Chopin', 'Johann Sebastian Bach', 'Antonio Vivaldi'),
        (306, 'Musique', 'Quel est le genre musical d''origine jamaïcaine connu pour ses rythmes syncopés ?', 'Le reggae', 'Le ska', 'Le calypso', 'Le dancehall'),
        (307, 'Musique', 'Quel compositeur a écrit "Les Quatre Saisons" ?', 'Antonio Vivaldi', 'Johann Pachelbel', 'Franz Schubert', 'Claude Debussy'),
        (308, 'Musique', 'Quel groupe a chanté "Stairway to Heaven" ?', 'Led Zeppelin', 'AC/DC', 'The Who', 'The Doors'),
        (309, 'Musique', 'Qui est l''auteur-compositeur-interprète de la chanson "Blowin'' in the Wind" ?', 'Bob Dylan', 'Johnny Cash', 'Neil Young', 'Bruce Springsteen'),
        (310, 'Musique', 'Quel chanteur est surnommé "The Boss" ?', 'Bruce Springsteen', 'David Bowie', 'Bob Dylan', 'Tom Petty'),
        (311, 'Musique', 'Quel orchestre est dirigé lors du Concert du Nouvel An à Vienne ?', 'L''Orchestre philharmonique de Vienne', 'L''Orchestre symphonique de Londres', 'L''Orchestre national de France', 'L''Orchestre de la Scala de Milan'),
        (312, 'Musique', 'Quel genre musical est associé à Bob Marley ?', 'Le reggae', 'Le rock', 'Le jazz', 'Le blues'),
        (313, 'Musique', 'Quel est l''instrument à clavier le plus couramment utilisé dans la musique classique ?', 'Le piano', 'L''orgue', 'Le clavecin', 'Le synthétiseur'),
        (314, 'Musique', 'Quel groupe de heavy metal est célèbre pour l''album "Master of Puppets" ?', 'Metallica', 'Iron Maiden', 'Black Sabbath', 'Slayer'),
        (315, 'Musique', 'Quel compositeur est connu pour sa symphonie n°9 "Ode à la joie" ?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Frédéric Chopin'),
        (316, 'Musique', 'Quel chanteur est surnommé "Le Roi de la Pop" ?', 'Michael Jackson', 'Elvis Presley', 'Prince', 'Freddie Mercury'),
        (317, 'Musique', 'Quel instrument est souvent utilisé dans le jazz pour les solos ?', 'Le saxophone', 'La guitare', 'Le violon', 'L’accordéon'),
        (318, 'Musique', 'Quel groupe britannique est connu pour l’album "Abbey Road" ?', 'The Beatles', 'The Rolling Stones', 'Pink Floyd', 'Queen'),
        (319, 'Musique', 'Quel style musical est né dans les années 1970 à New York ?', 'Le hip-hop', 'Le jazz', 'Le rock', 'Le reggae'),
        (320, 'Musique', 'Quel chanteur a interprété la chanson "Purple Rain" ?', 'Prince', 'David Bowie', 'Stevie Wonder', 'James Brown'),
        (321, 'Musique', 'Quel compositeur est célèbre pour "Les Quatre Saisons" ?', 'Antonio Vivaldi', 'Johann Sebastian Bach', 'Ludwig van Beethoven', 'Claude Debussy'),
        (322, 'Musique', 'Quelle chanteuse est connue pour la chanson "Rolling in the Deep" ?', 'Adele', 'Beyoncé', 'Lady Gaga', 'Rihanna'),
        (324, 'Musique', 'Quel compositeur est l’auteur de l’opéra "La Flûte enchantée" ?', 'Wolfgang Amadeus Mozart', 'Richard Wagner', 'Ludwig van Beethoven', 'Giuseppe Verdi'),
        (325, 'Musique', 'Quelle star du reggae est l’auteur de la chanson "No Woman, No Cry" ?', 'Bob Marley', 'Peter Tosh', 'Jimmy Cliff', 'Toots Hibbert'),
        (326, 'Musique', 'Quel instrument est souvent associé au blues ?', 'La guitare', 'Le piano', 'La batterie', 'Le violoncelle'),
        (327, 'Musique', 'Quel groupe a popularisé la chanson "Stairway to Heaven" ?', 'Led Zeppelin', 'The Rolling Stones', 'Pink Floyd', 'Deep Purple'),
        (328, 'Musique', 'Quelle est la nationalité du compositeur Frédéric Chopin ?', 'Polonaise', 'Française', 'Autrichienne', 'Allemande'),
        (329, 'Musique', 'Quel célèbre festival de musique a eu lieu en 1969 ?', 'Woodstock', 'Coachella', 'Glastonbury', 'Lollapalooza'),
        (330, 'Musique', 'Quelle chanteuse est connue pour la chanson "Like a Prayer" ?', 'Madonna', 'Whitney Houston', 'Cyndi Lauper', 'Janet Jackson'),
        (331, 'Musique', 'Quel groupe a sorti l’album "Dark Side of the Moon" ?', 'Pink Floyd', 'The Doors', 'The Who', 'The Rolling Stones'),
        (332, 'Musique', 'Quel instrument Yo-Yo Ma joue-t-il principalement ?', 'Le violoncelle', 'Le violon', 'Le piano', 'La contrebasse'),
        (333, 'Musique', 'Quel compositeur est à l’origine de l’opéra "Carmen" ?', 'Georges Bizet', 'Giuseppe Verdi', 'Richard Wagner', 'Wolfgang Amadeus Mozart'),
        (334, 'Musique', 'Quel rappeur est connu pour l’album "The Marshall Mathers LP" ?', 'Eminem', 'Jay-Z', 'Kanye West', 'Nas'),
        (335, 'Technologie', 'Quel est le langage de programmation principalement utilisé pour le développement d’applications Android ?', 'Java', 'Python', 'Ruby', 'C++'),
        (336, 'Technologie', 'Quel est le fondateur de Microsoft ?', 'Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'Elon Musk'),
        (337, 'Technologie', 'Quel est le moteur de recherche le plus utilisé dans le monde ?', 'Google', 'Bing', 'Yahoo', 'DuckDuckGo'),
        (338, 'Technologie', 'Quelle est l''unité de base de la donnée informatique ?', 'Le bit', 'Le byte', 'Le pixel', 'Le kilo-octet'),
        (339, 'Technologie', 'Quel est le langage de balisage utilisé pour structurer les pages web ?', 'HTML', 'CSS', 'JavaScript', 'XML'),
        (340, 'Technologie', 'Quel est le réseau social créé par Mark Zuckerberg ?', 'Facebook', 'Twitter', 'Instagram', 'LinkedIn'),
        (341, 'Technologie', 'Quelle entreprise a créé l’iPhone ?', 'Apple', 'Samsung', 'Google', 'Nokia'),
        (342, 'Technologie', 'Quel est le protocole de transfert de fichiers sur Internet ?', 'FTP', 'HTTP', 'TCP', 'SMTP'),
        (343, 'Technologie', 'Quel est l’acronyme de "Intelligence Artificielle" ?', 'IA', 'AI', 'IAR', 'II'),
        (344, 'Technologie', 'Quel est le nom du système d’exploitation développé par Google pour les smartphones ?', 'Android', 'iOS', 'Windows Phone', 'Symbian'),
        (345, 'Technologie', 'Quel langage est principalement utilisé pour les pages web dynamiques côté client ?', 'JavaScript', 'PHP', 'Python', 'Ruby'),
        (346, 'Technologie', 'Quel est le nom de la première souris d''ordinateur commercialisée ?', 'La souris Xerox', 'La souris Apple', 'La souris Microsoft', 'La souris IBM'),
        (347, 'Technologie', 'Quel protocole est utilisé pour sécuriser les transactions sur le web ?', 'HTTPS', 'HTTP', 'FTP', 'POP3'),
        (348, 'Technologie', 'En quelle année l''iPhone a-t-il été lancé ?', '2007', '2010', '2005', '2008'),
        (349, 'Technologie', 'Quelle entreprise a racheté LinkedIn en 2016 ?', 'Microsoft', 'Google', 'Apple', 'Amazon'),
        (350, 'Technologie', 'Quel est le langage de programmation principalement utilisé pour le développement front-end ?', 'JavaScript', 'C#', 'PHP', 'Swift'),
        (351, 'Technologie', 'Quel est le nom du célèbre assistant virtuel d’Apple ?', 'Siri', 'Alexa', 'Google Assistant', 'Cortana'),
        (352, 'Technologie', 'Quel appareil est utilisé pour mesurer l''intensité d’un courant électrique ?', 'Le voltmètre', 'Le thermomètre', 'Le baromètre', 'L''ohmmètre'),
        (353, 'Technologie', 'Quel est le créateur du langage de programmation Python ?', 'Guido van Rossum', 'James Gosling', 'Brendan Eich', 'Dennis Ritchie'),
        (354, 'Technologie', 'Quel terme désigne un réseau d''ordinateurs infectés utilisés pour mener des cyberattaques ?', 'Botnet', 'Malware', 'Spyware', 'Ransomware'),
        (355, 'Technologie', 'Quelle entreprise a développé le système d’exploitation Windows ?', 'Microsoft', 'Apple', 'Google', 'IBM'),
        (356, 'Technologie', 'Quel est le nom de la première carte mère utilisée dans les ordinateurs personnels ?', 'IBM PC', 'Apple II', 'Altair 8800', 'Commodore 64'),
        (357, 'Technologie', 'En quelle année le World Wide Web a-t-il été inventé ?', '1989', '1995', '2000', '1984'),
        (358, 'Technologie', 'Quel est le langage de requête utilisé pour interroger les bases de données ?', 'SQL', 'NoSQL', 'HTML', 'PHP'),
        (359, 'Technologie', 'Quelle est la capacité d’un disque compact standard (CD) ?', '700 Mo', '4,7 Go', '1 To', '128 Mo'),
        (360, 'Technologie', 'Quel est le format de compression audio populaire développé par Fraunhofer IIS ?', 'MP3', 'WAV', 'FLAC', 'AAC'),
        (361, 'Technologie', 'Quel appareil est utilisé pour protéger un ordinateur contre les surtensions ?', 'Parafoudre', 'Onduleur', 'Alimentation', 'Transformateur'),
        (362, 'Technologie', 'Quelle technologie est utilisée pour les paiements sans contact par carte bancaire ?', 'NFC', 'Bluetooth', 'Wi-Fi', 'Infra-rouge'),
        (363, 'Technologie', 'Quelle est la résolution standard du format d’image 4K ?', '3840 x 2160', '1920 x 1080', '1280 x 720', '7680 x 4320'),
        (364, 'Technologie', 'Quel est le nom du fondateur d’Amazon ?', 'Jeff Bezos', 'Elon Musk', 'Steve Jobs', 'Larry Page'),
        (365, 'Technologie', 'Quel logiciel est principalement utilisé pour la retouche photo professionnelle ?', 'Adobe Photoshop', 'GIMP', 'CorelDRAW', 'Adobe Illustrator'),
        (366, 'Technologie', 'Quel est le système de gestion de version le plus utilisé par les développeurs ?', 'Git', 'SVN', 'Mercurial', 'Bazaar'),
        (367, 'Technologie', 'Quel est le principal langage utilisé pour le développement d’applications iOS ?', 'Swift', 'Objective-C', 'Kotlin', 'Java'),
        (368, 'Technologie', 'Quel est le nom de la société qui fabrique les processeurs Ryzen ?', 'AMD', 'Intel', 'NVIDIA', 'Qualcomm'),
        (369, 'Technologie', 'Quel est l’acronyme du concept de la virtualisation des machines physiques ?', 'VM', 'AI', 'IP', 'RAID'),
        (370, 'Technologie', 'Quel est le réseau social orienté vers les professionnels ?', 'LinkedIn', 'Instagram', 'Twitter', 'Reddit'),
        (371, 'Technologie', 'Quel est l''outil le plus couramment utilisé pour créer des sites web réactifs ?', 'Bootstrap', 'jQuery', 'WordPress', 'Angular'),
        (372, 'Technologie', 'Quel est l’acronyme qui désigne le modèle de développement logiciel en open-source ?', 'FOSS', 'SaaS', 'IaaS', 'CMS'),
        (373, 'Technologie', 'Quel est le nom du réseau mondial d''ordinateurs connectés qui utilisent des protocoles standardisés pour communiquer ?', 'Internet', 'Intranet', 'Ethernet', 'Dark Web'),
        (374, 'Technologie', 'Quel est le nom du protocole qui permet de transférer des fichiers via Internet de manière sécurisée ?', 'SFTP', 'HTTP', 'SMTP', 'POP3'),
        (375, 'Sport', 'Quel pays a remporté la Coupe du Monde de la FIFA 2018 ?', 'La France', 'Le Brésil', 'L''Allemagne', 'L''Argentine'),
        (376, 'Sport', 'Quel joueur de basket est souvent considéré comme le plus grand de tous les temps ?', 'Michael Jordan', 'LeBron James', 'Kobe Bryant', 'Magic Johnson'),
        (377, 'Sport', 'Dans quel sport utilise-t-on un volant ?', 'Le badminton', 'Le tennis', 'Le squash', 'Le ping-pong'),
        (378, 'Sport', 'Quelle ville a accueilli les Jeux Olympiques de 2012 ?', 'Londres', 'Rio de Janeiro', 'Tokyo', 'Athènes'),
        (379, 'Sport', 'Quelle est la longueur d’un marathon en kilomètres ?', '42,195 km', '40 km', '50 km', '38,5 km'),
        (380, 'Sport', 'Quel pays a accueilli la première Coupe du Monde de la FIFA en 1930 ?', 'L''Uruguay', 'L''Italie', 'L''Angleterre', 'Le Brésil'),
        (381, 'Sport', 'Quel joueur de tennis détient le record du plus grand nombre de titres du Grand Chelem masculin ?', 'Rafael Nadal', 'Roger Federer', 'Novak Djokovic', 'Pete Sampras'),
        (382, 'Sport', 'Quel athlète a remporté 8 médailles d’or aux Jeux Olympiques de Pékin en 2008 ?', 'Michael Phelps', 'Usain Bolt', 'Carl Lewis', 'Mark Spitz'),
        (383, 'Sport', 'Dans quel sport le "putter" est-il utilisé ?', 'Le golf', 'Le billard', 'Le cricket', 'Le baseball'),
        (384, 'Sport', 'Quelle équipe a remporté la NBA Finals en 2021 ?', 'Les Milwaukee Bucks', 'Les Golden State Warriors', 'Les Los Angeles Lakers', 'Les Phoenix Suns'),
        (385, 'Sport', 'Qui est le pilote ayant remporté le plus de championnats du monde de Formule 1 ?', 'Michael Schumacher', 'Lewis Hamilton', 'Ayrton Senna', 'Sebastian Vettel'),
        (386, 'Sport', 'Quel pays est célèbre pour sa victoire en rugby lors de la Coupe du Monde 1995 ?', 'L''Afrique du Sud', 'La Nouvelle-Zélande', 'L''Angleterre', 'L''Australie'),
        (387, 'Sport', 'Quel boxeur est surnommé "The Greatest" ?', 'Muhammad Ali', 'Mike Tyson', 'Floyd Mayweather', 'Joe Frazier'),
        (388, 'Sport', 'Dans quel sport peut-on gagner la "Coupe Stanley" ?', 'Le hockey sur glace', 'Le baseball', 'Le football américain', 'Le basket-ball'),
        (389, 'Sport', 'Quel joueur de football est surnommé "La Pulga" ?', 'Lionel Messi', 'Cristiano Ronaldo', 'Neymar', 'Diego Maradona'),
        (390, 'Sport', 'Dans quelle discipline Michael Jordan est-il devenu une légende ?', 'Le basket-ball', 'Le baseball', 'Le football américain', 'Le tennis'),
        (391, 'Sport', 'Quel pays a remporté la médaille d’or au football masculin lors des Jeux Olympiques de 2016 ?', 'Le Brésil', 'L''Allemagne', 'L''Argentine', 'La France'),
        (392, 'Sport', 'Quelle est la distance de la piste de 100 mètres sprint ?', '100 mètres', '110 mètres', '90 mètres', '105 mètres'),
        (393, 'Sport', 'Quel joueur de tennis féminin a remporté 23 titres du Grand Chelem en simple ?', 'Serena Williams', 'Steffi Graf', 'Martina Navratilova', 'Chris Evert'),
        (394, 'Sport', 'Quel pays organise le tournoi de tennis de Wimbledon ?', 'Le Royaume-Uni', 'Les États-Unis', 'La France', 'L''Australie'),
        (395, 'Sport', 'Quel joueur de tennis a remporté le plus de titres du Grand Chelem féminin ?', 'Margaret Court', 'Serena Williams', 'Steffi Graf', 'Martina Navratilova'),
        (396, 'Sport', 'Quel pays a remporté la Coupe du Monde de rugby en 2019 ?', 'L''Afrique du Sud', 'La Nouvelle-Zélande', 'L''Angleterre', 'L''Australie'),
        (397, 'Sport', 'Quel sport se pratique avec un ballon ovale ?', 'Le rugby', 'Le football', 'Le handball', 'Le basket-ball'),
        (398, 'Sport', 'Quelle ville a accueilli les Jeux Olympiques d’hiver en 2014 ?', 'Sotchi', 'Vancouver', 'Turin', 'Pyeongchang'),
        (399, 'Sport', 'Quel coureur cycliste a remporté le Tour de France à 7 reprises avant d’être déchu de ses titres ?', 'Lance Armstrong', 'Eddy Merckx', 'Bernard Hinault', 'Miguel Indurain'),
        (400, 'Sport', 'Dans quel sport peut-on réaliser un "strike" ?', 'Le bowling', 'Le golf', 'Le tennis', 'Le baseball'),
        (401, 'Sport', 'Quelle équipe nationale de football est surnommée "La Roja" ?', 'L''Espagne', 'Le Chili', 'Le Portugal', 'L''Argentine'),
        (402, 'Sport', 'Quel club de football a remporté la Ligue des Champions 13 fois ?', 'Le Real Madrid', 'Le FC Barcelone', 'Le Bayern Munich', 'Manchester United'),
        (403, 'Sport', 'Quelle course automobile se déroule chaque année à Monaco ?', 'Le Grand Prix de Monaco', 'Les 24 Heures du Mans', 'Le Grand Prix d''Italie', 'Le Grand Prix de France'),
        (404, 'Sport', 'Dans quel pays a eu lieu la première édition des Jeux Olympiques modernes en 1896 ?', 'La Grèce', 'La France', 'L''Angleterre', 'Les États-Unis'),
        (405, 'Sport', 'Quel joueur de golf a remporté le plus de tournois majeurs ?', 'Jack Nicklaus', 'Tiger Woods', 'Arnold Palmer', 'Phil Mickelson'),
        (406, 'Sport', 'Quel joueur de football a remporté le Ballon d’Or 5 fois avant 2019 ?', 'Cristiano Ronaldo', 'Lionel Messi', 'Johan Cruyff', 'Zinédine Zidane'),
        (407, 'Sport', 'Quel athlète a couru le 100 mètres en 9,58 secondes ?', 'Usain Bolt', 'Carl Lewis', 'Tyson Gay', 'Justin Gatlin'),
        (408, 'Sport', 'Dans quel sport le terme "home run" est-il utilisé ?', 'Le baseball', 'Le cricket', 'Le football américain', 'Le rugby'),
        (409, 'Sport', 'Quel club de football anglais est surnommé "The Red Devils" ?', 'Manchester United', 'Liverpool', 'Chelsea', 'Arsenal'),
        (410, 'Sport', 'Qui a remporté le plus de titres NBA en tant que joueur ?', 'Bill Russell', 'Michael Jordan', 'Kobe Bryant', 'Magic Johnson'),
        (411, 'Sport', 'Quelle équipe de football a remporté le plus de Coupes du Monde ?', 'Le Brésil', 'L''Allemagne', 'L''Italie', 'L''Argentine'),
        (412, 'Sport', 'Quel est le nombre maximum de sets dans un match de tennis masculin en Grand Chelem ?', '5 sets', '3 sets', '7 sets', '4 sets'),
        (413, 'Sport', 'Quel sport utilise une batte, une balle et des buts appelés "wickets" ?', 'Le cricket', 'Le baseball', 'Le softball', 'Le handball'),
        (414, 'Sport', 'Qui est considéré comme le meilleur boxeur poids lourd de tous les temps ?', 'Muhammad Ali', 'Mike Tyson', 'Joe Frazier', 'George Foreman');